name: Expo Publish
on:
  push:
    branches:
      - prod-v2
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
      - name: "expo publish"
        run: expo publish --release-channel prod-v2
        env:
          GOOGLE_OAUTH_CLIENT: ${{ secrets.GOOGLE_OAUTH_CLIENT }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
